### ISSUE TITLE
withAuth -> custom hook 대체

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#112]
@brillante06 @bbumjun 
최근에서야 hook 과 hoc 간의 관계에 대해 자각하게 되었습니다. hook 이 없던 시절 리액트에서 컴포넌트를 재사용하기 위해 hoc 라는 걸 이용하게 되었는데 결국 hoc 로 인해 컴포넌트가 합성되고, props 를 두번씩 받기 때문에 type 지정이 굉장히 더러운걸 보셨을겁니다. 이렇게 컴포넌트가 더 무거워지고 복잡해지는 문제가 생깁니다. 그래서 hook 기능이 출시된 현재로서는 굳이 hoc 로 만드는것 보다는 hook 을 이용해서 재사용 로직을 분리하는게 바람직해 보입니다.

따.라.서 withAuth 는 별도의 custom hook 으로 대체하겠습니다.

- https://velog.io/@vies00/React-Hooks
- https://www.slideshare.net/ShoppingNAVER/react-hooks-177289990

**Comment by bbumjun** [comment]
좋습니다.!!
