### ISSUE TITLE
container component 제거

### ISSUE THREAD

**Issue by bbumjun** [Lee-Park-Bae-Project/KAKIOTALK#119]

**Comment by Junow** [comment]
@bbumjun 현재 [feature/room-refactor](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/pull/115) 브랜치에 이어서 진행중인 작업인가요?

**Comment by bbumjun** [comment]
> @bbumjun 현재 [feature/room-refactor](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/pull/115) 브랜치에 이어서 진행중인 작업인가요?

아직 작업 시작은 안했습니다.ㅎㅎ 다른 브랜치를 한번 머지하고 시작하는게 좋을까요?

**Comment by Junow** [comment]
chat room container 삭제 되었습니다. - af9bf2f
