### ISSUE TITLE
[배포] 자동배포 스크립트

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#128]
@brillante06 

저번 회의 마지막에 문제있었던 서버 자동 배포문제는 어떻게 되었나요?

**Comment by brillante06** [comment]
pm2-runtime start라는 명령어로 바꿔 실행을 했더니 서버가 동작은 하지만 pm2 자체가 불완전하게 동작하여 조금 더 알아보는 중입니다. 현재 서버는 정상적으로 사용가능합니다.

**Comment by Junow** [comment]
pm2 정상 적용 될때까지 열어둘게요
