### ISSUE TITLE
[배포] 클라이언트 - 트래비스 배포

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#134]
@brillante06 트래비스에서 클라이언트 배포될때 어떤 과정을 거치고 있나요? 지금 배포된 주소 들어가보면 이전 소스코드에 있던 예전 서버 주소(`http://34.64.!@#`)로 요청을 보내고 있는것 같은데 최신 소스코드가 반영이 안된것 처럼 보입니다.

**Comment by brillante06** [comment]
재설정했습니다. 지금 하는 작업 특정 브랜치에서 할 수 있도록 해드릴테니 하고 있는거 push 한번 해주세요

**Comment by Junow** [comment]
@brillante06 어떤 부분이 바뀌었나요?

혹시 수동으로는 배포가 안되나요? 딱히 푸쉬할게 없는데;

**Comment by brillante06** [comment]
트라비스가 깃헙에 있는 코드를 인식해서 배포를 해주는거라 찾아봤더니 수동 배포에 대한 내용은 없네요

**Comment by brillante06** [comment]
그러면 현재 올라가 있는 브랜치에서 재빌드를 하겠습니다

**Comment by Junow** [comment]
방금 푸쉬했습니다.

**Comment by Junow** [comment]
오호 일단 서버연결은 됐습니다. 소켓은 아직도 말썽인데 지금 제 브랜치에 푸시하면 자동배포되는 상황인가요?

**Comment by brillante06** [comment]
네 현재는 브랜치 인식해서 자동배포 되고 있습니다

**Comment by Junow** [comment]
`feature/api-server-https` 브랜치 맞죠? 여기다가 푸시하면서 소켓 연결 고쳐놓겠습니다.

**Comment by brillante06** [comment]
![image](https://user-images.githubusercontent.com/22672155/87702675-a7c63380-c7d4-11ea-90d6-17f51fdae0ff.png)
넵 배포되고 있습니다

**Comment by Junow** [comment]
오늘 새벽 4시 쯤에 `feature/api-server-https` 브랜치 클라이언트 배포 나갔나요? 뭐하나 고쳤는데 변화가 없네요 ㅠ

**Comment by brillante06** [comment]
travis.yml을 수정해서 다시 push해야할것같네요
