### ISSUE TITLE
[UI] 채팅방 하나도 없을때 안내문구 추가

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#149]
@bbumjun @brillante06 
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/bacdbead-e2a1-4120-aeff-244dd03a2bce)

방이 한개도 없을때 아무말도 없으니 허전하네요 뭐라도 넣어야겠습니다.

**Comment by brillante06** [comment]
채팅 아이콘을 클릭해 친구들과 대화해보세요^_^
