### ISSUE TITLE
[배포] gh-page에 배포할때 router를 어떻게 쓰면 좋을지

### ISSUE THREAD

**Issue by brillante06** [Lee-Park-Bae-Project/KAKIOTALK#151]
현재는 gh-page의 안정적이지 못한 호스팅으로 인해서 hash router를 쓰고 있었습니다.
근데 이번에 대화방을 만들고 roomSaga안에서 리다이렉트하는 과정에서 hash router를 쓰지 못하게 되어서 router를 쓰고 로컬에서는 잘 작동을 하지만 이렇게 되면 배포를 했을때 새로고침을 한다던가 리다이렉트를 할때 404페이지가 뜨는 상황이 발생합니다. 공식 홈페이지에서 제공하는 방법을 써봐도 달라지는 점은 없었습니다.

그래서 리다이렉트를 saga안에서 하는걸 버리고 기존에 사용하던 hash router를 쓸지 
아니면 router로 교체를 한 후 그 뒤 다른 방법을 찾아야 할지 고민해봐야할 것 같습니다.

gh-page 배포 이슈 관련 글
[공식홈페이지 글](https://github.com/rafgraph/spa-github-pages)
[스택오버플로우에 나온 해결 방법 3가지](https://stackoverflow.com/questions/62047422/404-when-trying-to-enter-a-react-app-route/62050700#62050700)

**Comment by Junow** [comment]
올려주신 링크처럼 `404 pages` 를 따로 만들어서 index 로 `redirect` 하는게 안된거는 거죠?

### `redirect` 를 사가 밖에서 처리한다
이거는 사실 에러상황이 saga 안에서 잡히는데 그 처리는 saga 밖에서 처리하면 그것대로 비즈니스 로직이 꼬이는 것 같구요. saga 와 그 밖에서 이루어지는 routing 의 연결을 만드는게 또 하나의 과제가 되겠네요

### custom 404 page
http://spa-github-pages.rafrex.com/example 여기서 보시면 아시겠지만 페이지 url 이 두번씩 바뀌는걸 보실 수 있는데요 사실 이 방법은 github pages 가 spa 를 지원하지 않는걸 피하기 위한 편법이지 저희가 겪고 있는 문제를 해결할 수 있는 방안은 아니라고 봅니다. 

일단 생각나는 거는 [error boundary](https://ko.reactjs.org/docs/error-boundaries.html) 를 이용할 수 있겠는데 여기서 `404 error` 가 잡히는지는 잘 모르겠구요. 처음에 쓰려고 했던 `now.sh` 를 이용해볼 수 있겠네요

저번에 올려줬던 https://jbee.io/react/react-4-react-router/ 여기나온 코드로는 동작이 왜 안되나요?

**Comment by brillante06** [comment]
올려주신 코드로는 정상작동합니다.

하지만 제가 위에서 언급한것처럼 배포했을때 오류가 나기 때문에 바꿔야 할 것 같네요.
그리고 깃허브에서 제공해주는 방법으로도 이미 시도해보았지만 크게 바뀌는 것은 없었습니다. 

error boundary는 처음 듣는데 그걸 알아보거나 now.sh를 사용하는 방향으로 가야할 것 같네요

**Comment by Junow** [comment]
네 그러면 일단 일대일 채팅 기능 개발하시던거는 routing 처리 다른데서 하는 걸로 일단 푸시하고 다음 스프린트에 routing 고쳐보도록 할까요

**Comment by brillante06** [comment]
네 일단 router로 redirect가능하게 하는걸로 하고 대화상대 초대 ui 해결하도록 할게요

**Comment by Junow** [comment]
아뇨 지금 브랜치는 일대일 기능 까지만 해서 머지하는 거롤 하고 ui 해결은 다른 브랜치에서 하시죠
