### ISSUE TITLE
Client Request 객체 리팩토링

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#160]

**Comment by Junow** [comment]
@brillante06 @bbumjun 
지금 request 객체 변경하고 있는데 대충 이렇게 생겼구요.
```typescript
async function Axios<T>(config: AxiosRequestConfig) {
  try {
    const response = await instance.request<ResponseType<T>>(config)
    return response.data.data
  } catch (e) {
    throw new Error(e)
  }
}
```

문제는 이게아니라 client, server 서로 api 주고받으면서 타입이 서로 안맞거나 타입 선언이 분산되어 있네요 이걸 common package 에 몰아두고 싶거나 하고싶은데 좋은 방법 있을까요?

**Comment by Junow** [comment]
@brillante06 
`request.ts/makeRoomRequest` 의 리턴값은 뭔가요? 서버쪽 controller 하고 안맞는 부분이 있어보이네요

```typescript
export const makeRoomRequest = (args: Type.InviteUser[]) => Axios<Pick<Models.Room, 'uuid'>>({
  method: 'POST',
  url: '/chat/room',
  data: { args },
})
```

![image](https://user-images.githubusercontent.com/32632221/89557091-429eb480-d84d-11ea-9756-74d55efd4af5.png)

![image](https://user-images.githubusercontent.com/32632221/89557131-50543a00-d84d-11ea-8671-74915f853cfb.png)

**Comment by brillante06** [comment]
request는 이렇게 바뀌면 될 것 같습니다.

`export const makeRoomRequest = (args: Type.InviteUser[]) => 
Axios<{Rooms: Pick<Models.Room, 'uuid' | 'participants'>[] uuid: string}>({
  method: 'POST',
  url: '/chat/room',
  data: { args },
})`

**Comment by Junow** [comment]
언제한번 날잡고 전체 api 타입 체크 해봐야할것같아요
