### ISSUE TITLE
[버그] socket joinRooms 실행 언제해야할지?

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#162]
@bbumjun @brillante06 

원래는 `joinRooms` 가 `roomSaga` 안에서 방정보 가져올때 방 새로 만들때 실행되고 있었는데 `redux-persist` 도입이후 action 을 dispatch 하지 않아서  `roomSaga` 실행이 안되서 socket 방입장이 안됩니다.

**Comment by brillante06** [comment]
채팅방 목록을 클릭했을때 joinRoom하면 안되나요?

**Comment by Junow** [comment]
그렇게해도 되긴 하겠지만 채팅목록을 한번도 클릭하지 않는다면 방에 못들어가서 채팅이벤트 수신이 불가능합니다 ㅠ 로그인이후에 하면 되려나요

**Comment by Junow** [comment]
@bbumjun 
`redux-persist` 는 모든 state 르 저장해두고 dispatch 되는 action 들을 막는건가요? 채팅 데이터 같은 경우에 나중에 다시 접속했을때 접속하지 않은동안 쌓인 메시지들을 요청할 수 있어야할 거 같은데 그 부분은 어떻게 처리할 수 있나요?

**Comment by bbumjun** [comment]
넵. `getRooms`같은 액션은 스토리지 저장과 상관없이 새로고침이나 렌더링을 기준으로 매번 디스패치 해야할것 같네요.
