### ISSUE TITLE
[배포] 상태코드 수정

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#165]
@bbumjun @brillante06 
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/30e812ab-3db2-4aae-bc71-6772bb2a2a84)

배포된 페이지에서 에러가 나니까 보기 안좋네요 `NODE_ENV===deployment` 면은 400 이상의 상태코드를 200으로 바꾸고 보내도 될까요?

**Comment by Junow** [comment]
@bbumjun @brillante06 
상태코드를 수정해볼까합니다. restful 하게 하는것도 의미가 있겠지만 하나하나 맞춰주려니 끝도 없는것 같아서 간단하게 바꾸려고해요. 

클라이언트 쪽에서 에러처리는 200 응답을 받았을떄 error 가 throw 되지 않으니 `success` 값으로 판단해야겠습니다.

```typescript
// success (상태코드 200)
{
  success: true,
  data: Object,
  message: "",
}
// fail
{
  success: false,
  data: {},
  message: "적당한 실패 메시지",
}
  



```

**Comment by brillante06** [comment]
좋습니다 이렇게 하면 에러도 확인할 수 있겠네요

**Comment by Junow** [comment]
일단 브랜치파서 진행하겠습니다

**Comment by Junow** [comment]
@brillante06 @bbumjun 
성공 / 실패 에 따른 상태코드는 어떻게 처리할까요?

200 / 500 으로 생각중입니다만

**Comment by Junow** [comment]
```typescript
async function Axios<T>(config: AxiosRequestConfig) {
  try {
    const response = await instance.request<ResponseType<T>>(config)
    if (response.data.success) {
      return response.data.data
    }
    throw new Error(response.data.message)
  } catch (e) {
    // Store.store.dispatch(logoutRequest())
    throw new Error(e.message)
  }
}
```

지금 위 코드에서 주석되있는 부분이 `dispatch` 하는 부분인데 이걸로 에러발생시 리덕스에서 액션 잡아서 `alert` 를 띄워주도록 하는건 어떨까요?

**Comment by bbumjun** [comment]
> ```ts
> async function Axios<T>(config: AxiosRequestConfig) {
>   try {
>     const response = await instance.request<ResponseType<T>>(config)
>     if (response.data.success) {
>       return response.data.data
>     }
>     throw new Error(response.data.message)
>   } catch (e) {
>     // Store.store.dispatch(logoutRequest())
>     throw new Error(e.message)
>   }
> }
> ```
> 
> 지금 위 코드에서 주석되있는 부분이 `dispatch` 하는 부분인데 이걸로 에러발생시 리덕스에서 액션 잡아서 `alert` 를 띄워주도록 하는건 어떨까요?

좋은 방법이네요 에러에 대처하는 액션을 통일할 수 있겠네요 👍

**Comment by Junow** [comment]
일단 그냥 모든 에러 상태코드 500 로 통일했습니다.

서버의 `common/utils.ts` 의 `response` 함수는 모든 에러코드를 200으로 바꿔주는 대신 `success` 값을 `false` 로 세팅해서 응답을 내려줍니다.
