### ISSUE TITLE
채팅 기능 (소켓)

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#39]
소켓연결로 채팅 기능 개발

**Comment by Junow** [comment]
@Lee-Park-Bae-Project/team 
특정 사람에게 이벤트를 발생시켜주려면 로그인 된 사람마다의 socketId 를 기억해둘 필요가 있어보이는데요. socketId를 어디다 두면 좋을까요?? 디비나 레디스 정도 생각이 듭니다.
아니면 채팅 할 때 다른 방식으로 할 수 있으면 아이디어좀

**Comment by Junow** [comment]
@brillante06 @bbumjun

**Comment by bbumjun** [comment]
@Junow  디비보단 레디스가 더 적합하다고 생각합니다 !!

**Comment by Junow** [comment]
@bbumjun @brillante06 
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/d3ea89c9-ec05-4acc-b440-4362a56480eb)

정리할겸 만들어봤습니다

**Comment by brillante06** [comment]
오우 너무 좋습니다
깔끔하군여

**Comment by bbumjun** [comment]
홀리
