### ISSUE TITLE
데이터베이스 관계 수정 (chat - room_participants)

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#47]
@bbumjun @brillante06 
지금 chat table 에서 room_id, sender_id가 room_participants 의 user_id, room_id를 foreign key로 가지고 있는데

생각해보니 room_participants 의 foreign key 를 chat의 foreign key 로 가지고 있는게 이상해서요

지금 특정 방의 chat 들을 모두 가져오기 위해서는 chat.findAll(incluse: {model: User}) 같은 식으로 쿼리를 작성해야 하는데 이 쿼리 모습은 chat 이 user 와 관계를 맺고 있는 것이거든요?

이중으로 외래키 조건을 걸려면 chat table 에서 room_participants 를 가지고 있는 foreign key 하나 가지고 있는게 맞지 않을까요? 

chat.room_participants_id 가 room_pariticipants 의 id 를 foreign key 로 가지고 있는 형태죠

그래서 sequelize 로 데이터를 가져올 때 chat 의 room_participants_id 를 include 하고 그 안에서 user_id, room_id 를 가져오는게 좀더 맞는 관계 설정인것 같습니다.

**Comment by bbumjun** [comment]
잘 이해했습니다. chat-room_participants-user를 이중으로 연결할 외래키를 갖는 것이 필요하다는 말씀이군요

**Comment by Junow** [comment]
넹, 
chat.room_participants_id 가 추가될거고
chat.sender_id, chat.room_id 는 삭제하면 될것 같습니다.

**Comment by Junow** [comment]
수정되었습니다.
