### ISSUE TITLE
response 객체 property 변경

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#50]
@bbumjun @brillante06 
현재는
```typescript
{
  success: boolean,
  body: any,
}
```
이렇게 되있어서 서버가 주는 메시지를 data 안에다 넣고 response 하는 형태인데
이제
```typescript
{
  success: boolean,
  message: string,
  body: any,
}
```

로 바꿔보는게 어떨까요 api test 작성하다 보니 메시지를 따로 두는게 반환받는 response 에 데이터와 메시지가 둘다 있을때 구분하기가 쉬울것 같아요

**Comment by Junow** [comment]
@Lee-Park-Bae-Project/team 어떠세여

**Comment by bbumjun** [comment]
@Junow 좋은 생각인거 같아요 수정해서 올려주시면 저도 반영할게요

**Comment by Junow** [comment]
@Lee-Park-Bae-Project/team 
여기에 더해 아래처럼 axios response 에 들어오는 데이터에 대한 타입 추론이 가능하도록 리팩토링 중에 있습니다.

```typescript
export type ResponseType<T> = {
  success: boolean;
  data: T;
}

export type ApiCallback<T = {}> = (
  err: AxiosResponse<ResponseType<T>> | null,
  response?: AxiosResponse<ResponseType<T>>,
) => void

async function Axios<T>(config: AxiosRequestConfig) {
  return instance.request<ResponseType<T>>(config);
}

getRooms: () => Axios<Type.ChatRoom2>(getRooms),
```

아래 사진처럼 api 요청마다 받아오는 데이터에 대한 추론이 가능합니다.
![image](https://user-images.githubusercontent.com/32632221/81849545-a177c900-9591-11ea-9bad-c17ed4540f3f.png)

여기 [링크](https://eunajjing.github.io/2019/05/27/woowahan04/) 처럼 모든 axios 요청을 promise 로 감싸놓는다면 에러처리나 중복 코드 제거에 더 좋을 것 같구요

현재까지 진행사항은 `chat-socket` 브랜치 `client/src/common/request.ts`에 들어있습니다.

**Comment by Junow** [comment]
#165 에 포함
