### ISSUE TITLE
api 서버, 클라이언트 타입 이름 통일

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#65]
지금 chat-socket 브랜치에서 채팅방 목록 받아오는 api 만들고 react 랑 연동하고 있는데요. 서버쪽이랑 react 쪽이랑 타입 부분에서 사용하는 용어가 달라서 통일이 필요해 보입니다. 나중에가서 터질바에 지금 고치고 넘어가는게 좋을것 같습니다.

예를들면, 
room - chatRoom,
participants - sender,
userList - users
id - uuid
status - statusMessage
msg - message
lastModified - updatedAt
등이 있습니다.

**Comment by brillante06** [comment]
서버나 클라한쪽으로 통일하기에는 무리가 있을 것 같고
저는
room - chatRoom -> **chatRoom**
participants - sender, ->이 용어는 달라야한다고 생각합니다.
userList - users -> **users**
id - uuid -> **uuid**
status - statusMessage -> **statusMessage**
msg - message -> **message**
lastModified - updatedAt -> **updatedAt**

**Comment by Junow** [comment]
언제한번 개발중지하고 날잡고 이런거나 수정하죠

**Comment by brillante06** [comment]
이번주 토로 하시져

**Comment by bbumjun** [comment]
이번주 미팅때 통일해봅시다~~

**Comment by Junow** [comment]
토욜까지 개발완료하는 걸로 할까요
디벨롭에 다 머지시키고 일욜날 손보는 걸루

**Comment by brillante06** [comment]
좋아요 일욜날 미팅때 수정하는걸로 알겠습니다!

**Comment by bbumjun** [comment]
```

user {
uuid,
name,
statusMessage,
email,
}
chat {
 uuid,
content,
sender,
roomId,
createdAt,
}
room{
participants,
uuid,
lastMessage,
numOfNewMessages
updatedAt,
}


```
