### ISSUE TITLE
클라이언트 User interface 에 Email property 추가가 필요함

### ISSUE THREAD

**Issue by bbumjun** [Lee-Park-Bae-Project/KAKIOTALK#68]
@Lee-Park-Bae-Project/team 
클라이언트에서 User 인터페이스로 현재
`
export interface User {
  id: string;
  userName: string;
  statusMessage: string;
}
`

이렇게 가지고 있는데
친구 추가 할 때 친구의 계정을 구별할 수 있는 값으로 중복되지 않으면서 유저에게 의미있는 값이여야 합니다
근데 User가 가지고 있는 id 값은 숫자로만 이루어진 google id 여서 부적절하다고 생각됩니다
그래서 email property를 추가로 가져야 할것 같아여

**Comment by Junow** [comment]
uuid 를 쓰면 될것같습니다
