### ISSUE TITLE
[긴급] Sequelize Model Definition

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#70]
@bbumjun @brillante06 
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/e6a54633-c3f3-4969-93e0-d0ba1c79d077)

위와같은 에러가 갑자기 발생했는데요

살펴보니 각 모델에 대한 find 연산 후 나오는 데이터가 any 타입인걸 알 수 있습니다.
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/30d6993b-3f5e-4e31-945f-fc307ab5c18a)

그렇다면 rooms 가 어떤 property 를 가지고 있는지에 대해 tsc 가 전혀 이해하지 못하는 것이라 할 수 있는데요. 이전에는 왜 문제가 발생하지 않았는지는 모르겠습니다. 

공식문서에는 다음과 같이 Model을 확장한 새로운 MyModel 타입을 명시해주고 있습니다.
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/1d1e605d-a1e7-4383-8dc7-781c01b73fef)

저희는 현재 Model 타입을 확장하지 않고 IUser 를 그대로 넣어 주었네요
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/03abb811-fba5-43de-bb2f-0830866c201b)

실험은 해봐야겠지만 IUserModel 을 정의해 줘야할 것 같습니다.
```typescript

interface IUserModel extends Model, IUser {}

export type UserStatic = typeof Model & {
  new (values?: object, options?: BuildOptions): IUserModel;
  associate: (models: any) => void;
}

```

**Comment by Junow** [comment]
@brillante06 @bbumjun 
급하게 고치긴 했습니다만 /models/user.ts, /models/room.ts 에서 서로 UserModel, RoomModel 을 참조하고 있는데 순환참조 에러가 안나네요? 찝찝하지만 문제가 없으니 일단 두겠습니다.

각 모델을 정의할 때 UserModel 인터페이스 안에다가 모델의 attributes 를 정의해줘도 되지만 다른 곳에서 모델에 대한 데이터를 쓸일도 있지 않을까? 해서 일단 types/ 폴더에 따로 빼두었습니다.

![image](https://user-images.githubusercontent.com/32632221/82154987-9fbd4680-98ac-11ea-990c-8c36a116f408.png)

![image](https://user-images.githubusercontent.com/32632221/82154990-a946ae80-98ac-11ea-9970-05bb1ed6e177.png)

![image](https://user-images.githubusercontent.com/32632221/82154997-c24f5f80-98ac-11ea-96cb-2edce7bcd32a.png)
![image](https://user-images.githubusercontent.com/32632221/82155005-d7c48980-98ac-11ea-9ec6-45aa305565c9.png)
![image](https://user-images.githubusercontent.com/32632221/82155012-e57a0f00-98ac-11ea-9ed7-469cbb83fc79.png)
include 해서 as 로 alias 를 이용할 때 someData.[alias] 가 있다는 걸 명시해주기 위해서 UserModel 에 정의해 두었습니다. 

alias 도 여기저기서 원시값으로 존재하는게 꼴보기 싫어서 변수로 빼두었습니다. 모든 alias 들은 models/index.ts 에서 export 하고 있으니 사용하시면 됩니다.

![image](https://user-images.githubusercontent.com/32632221/82155036-15291700-98ad-11ea-9c2e-6af39cca3936.png)

**Comment by bbumjun** [comment]
@Junow 
순환참조에 대한 부분을 제외하고는 잘 이해했습니다.
머지 후  어제 논의햇던 타입 통일에 대한 부분 수정해보도록 하겟습니다
