### ISSUE TITLE
메인화면 진입 에러

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#75]
@bbumjun @brillante06 
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/75d9bf0e-398d-466a-9232-f847d00c3410)

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/f8c4ecdb-bfed-4881-8f1b-2e6f24fa0b1f)

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/9c94035d-c82d-4b12-aadf-7a648d6b3600)

로그인안하고 메인화면 들어가면 이러네요

**Comment by bbumjun** [comment]
이 이슈는 현재 제 브랜치에서 해결해놨습니다 !
