### ISSUE TITLE
무중단 배포 cloudbuild.yaml 파일 문제

### ISSUE THREAD

**Issue by brillante06** [Lee-Park-Bae-Project/KAKIOTALK#78]
무중단 배포를 위해 cloudbuild.yaml 파일 설정을 하려고 하는데 오류 해결을 못하고 있습니다.
여러분들의 도움이 필요해요

**Comment by Junow** [comment]
무슨에런가요

**Comment by brillante06** [comment]
failed unmarshalling build config cloudbuild.yaml: yaml: line 3: did not find expected '-' indicator
