### ISSUE TITLE
[긴급] 모델 uuid default value 변경

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#79]
chat 을 생성하면서 알수 없는 이유로 `defualtValue: uuid()` 가 제대로 동작하지 않고 같은 값을 만들어내어 unique constraint 에러가 발생합니다. 그래서 `defqultValue: dataTypes.UUIDV4,` 로 변경되어 데이터 포맷이 살짝 바뀌었으니 이점 숙지하시기 바랍니다.

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/74ec8c2f-9e5c-4ff3-a9b2-76275fd8a71b)

밑에 중간중간 - 가 붙은게 dataTypes.UUIDV4 입니다

**Comment by Junow** [comment]
마지막 확인자는 이슈 닫아주세요

**Comment by Junow** [comment]
@brillante06 @bbumjun

**Comment by bbumjun** [comment]
확인했습니다~

**Comment by brillante06** [comment]
확인했습니다~!
