### ISSUE TITLE
socket 중복 이벤트 발생

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#80]
채팅 보내고 응답으로 소켓이벤트를 받는데 2번 중복으로 발생을하네요

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/c905c9ab-b2ab-45be-ad5e-915f7f7f6d9b)

기존에는 `socket/index.ts` 에서 아래와 같이 함수를 작성하고 `chatRoom` 컴포넌트에서 이벤트를 등록해줍니다.

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/28458e64-a097-4cce-bb96-8992f0590939)
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/b64c77d6-fe10-4771-b986-e7c18b1e243f)

이벤트가 여러번 등록되는게 아닐까 싶어서 `socket.hasListeners` 프로퍼티를 이용해서 값을 찍어봤습니다. 아래와같이 두번 등록이 되는군요. 아마 컴포넌트 생성시에 `useEffect` 에서 1번, 어떤 이유에서든지 다시 렌더링하면서 1번 일어나는 것 같습니다.

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/f34f835a-16ea-4b8b-8278-592c3ec5d37a)
![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/5bd46eb1-c8d5-4ff0-84b0-a0e3f7e3e10a)

그리고 다시 재현해보니 `useEffect` 가 1번만 실행 되구요 이벤트는 3번 등록이 되었습니다. ?????????
제 생각과는 다른 방식으로 컴포넌트가 실행되고 있었군요. 이 사건에 대해선 다시한번 조사해봐야겠습니다.

그래서 그냥 `useEffect` clean-up 으로 특정 소켓 이벤트를 제거하도록 만들었습니다.
사실은 현재 채팅방이 두개인데 1번 채팅방에 들어갔을때도 이벤트가 등록되고 2번 채팅방에 들어갔을때도 이벤트가 등록되고 이러면 방에 들어간 횟수만큼 이벤트 콜백이 실행이 되겠죠. 실제로 방을 2번 들어가면 2번실행, 3번들어가면 3번이 실행됩니다. 하지만 clean-up 에서 이벤트를 제거해버리면 chatRoom 이 렌더링 될 때마다 1개의 이벤트가 등록되고 chatRoom 이 DOM 에서 떨어질때마다 이벤트가 제거되기 떄문에 정확히 한개의 이벤트만 등록이 가능하게 됩니다.

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/111639ba-1f42-4b2d-a53c-5650341b3a53)

![image.png](https://images.zenhubusercontent.com/5e43b6707e875a19be6be4c8/756f0297-1aaf-40f3-b27d-9de3513e9eef)

**Comment by Junow** [comment]
@bbumjun @brillante06 
흥미로운 사건에 대해 공유드립니다

**Comment by bbumjun** [comment]
@Junow 
오호
참고하도록 하겠습니다

**Comment by brillante06** [comment]
@Junow 
좋습니다~다른 기능구현할때 참고해야겠네요
