### ISSUE TITLE
리덕스 비동기 값 렌더링 이슈

### ISSUE THREAD

**Issue by Junow** [Lee-Park-Bae-Project/KAKIOTALK#81]
@bbumjun @brillante06 
채팅방에서 자신 메시지를 `flex-direction: row-reverse` 상대방 메시지는 `flex-direction: row` 로 처리하고 있는데요

채팅방에 처음 입장할 때 자신의 모든 메시지가 왼쪽으로 치우쳐 있다가 오른쪽으로 이동하는 현상이 가끔 목격되네요.

`withAuth`를 통해 자신의 `uuid`, `getChats` 을 이용해 `chat.uuid` 를 가져오는데 비동기로 딜레이 차이가 길어질 수록 자신의 메시지인지를 판단하는 `ChatBox` 컴포넌트의 `sender.uuid == userUuid` 가 `false` 가 되어 그런것 같습니다.

채팅방에서 방 제목또한 리덕스 값을 가져오는데 방으로 직접 접근하는 경우 (방목록에서 방을 선택하지 않고 url 로 이동하는 경우) 관련 이슈가 있어서 리덕스 데이터가 업데이트 되는 시점에 대해 좀더 생각해 봐야할 것 같습니다. 비동기 리덕스 업데이트를 사용하는 어떤 컴포넌트에서라도 나타날 수 있는 문제니까요.

**Comment by brillante06** [comment]
재밌네요 조금더 고민해보면 좋을 문제인것 같습니다.

**Comment by bbumjun** [comment]
말씀해주신 것과 비슷한 이슈인지는 모르겠지만 저같은 경우는 메인페이지를 렌더링 할 때마다 비동기 리덕스 업데이트를 통해 친구목록을 가져오려고 하는데요, `withAuth` 를 통해서 로그인 인증을 하기 전에 친구목록 업데이트를 `dispatch` 하기 때문에 `server`에서 불필요한 `500 error`를 주는 문제가 생깁니다. 또 렌더링할때마다 서버에 친구데이터를 요청하니 비효율적이기 그지없습니다. 이에 대한 해결책으로 생각해본 것은 `redux store`에서 로그인 여부에 대한 `boolean state`를 갖고 필요한 데이터의 비동기 `dispatch` 여부를 판단하도록 구현하는 것입니다.

**Comment by Junow** [comment]
> 로그인 인증을 하기 전에 친구목록 업데이트를 dispatch

혹시 이 요청 보낼때 서버에서 isAuth 미들웨어 타면 걸러지지 않나요??

**Comment by bbumjun** [comment]
> > 로그인 인증을 하기 전에 친구목록 업데이트를 dispatch
> 
> 혹시 이 요청 보낼때 서버에서 isAuth 미들웨어 타면 걸러지지 않나요??

네 no token 에러로 response 오는데 로그인 전에는 getFriend 요청 보내는것 자체가 불필요하다고 생각해서 저렇게 고쳐봤어요

**Comment by Junow** [comment]
넵 좋습니다
