### ISSUE TITLE
로그인 여부를 확인할 수 있는 redux login state 추가

### ISSUE THREAD

**Issue by bbumjun** [Lee-Park-Bae-Project/KAKIOTALK#82]
@brillante06 @Junow 
기존의 메인 페이지에서는 `useEffect`를 사용해 페이지가 새로 렌더링 될 때마다 `redux-saga`를 통해서 서버에 데이터 요청을 해왔습니다. 이 방식은 `withAuth` 를 통해 로그인 여부를 판단하기 전에 실행되서, 카키오톡에 처음 접속했을 때 불필요한 요청을 보내고 불필요한 에러를 `alert`하는 문제가 있었습니다. 또한 접속중에 새로고침을 했을 때에도 `store`에 저장된 값을 활용하지 않고 계속 서버로 같은 요청을 매번 보내는 비효율적인 행동을 하고 있었습니다.

그래서 `redux store`에서 `login state`를 갖도록 하고 `googleSignIn` 컴포넌트 내부와 `main` 컴포넌트에서 `login action`을 `dispatch`하도록 했습니다. 이제 렌더링할 때마다 서버에 데이터를 요청하지 않고 `withAuth`를 거쳐 로그인을 성공한 이후에만 서버에 값을 요청할 수 있습니다. 기존에 작성되어 있던 로그인 모듈에서 리팩토링 했고 앞으로 사용되지 않는 ` loginSaga` 관련 코드는 삭제하겠습니다.

아래는 로그인 모듈의 리듀서 내용과 컴포넌트에서 로그인 됐을 때의 `useEffect`내부 로직입니다
![image.png](https://images.zenhubusercontent.com/5eae5ec8e0da2c10612d1c79/a8d78072-10de-4858-8a08-a30b59c50a1f)

![image.png](https://images.zenhubusercontent.com/5eae5ec8e0da2c10612d1c79/1d82ef26-3637-4441-b8f0-3f9d934ca3c2)

**Comment by Junow** [comment]
@bbumjun 
아예 withAuth hoc 에다가 login state 업데이트 하는걸 붙여넣는건 어떨까요?

**Comment by bbumjun** [comment]
> @bbumjun
> 아예 withAuth hoc 에다가 login state 업데이트 하는걸 붙여넣는건 어떨까요?

저도 그게 훨씬 직관적이라고 생각해서 그렇게 구현해봤는데 withAuth가 컴포넌트가 아니라서 내부에서 dispatch를 사용할수가 없다고 하더라구요. 대안으로 저 두군데에다가 dispatch를 심어놨습니다

**Comment by Junow** [comment]
> > @bbumjun
> > 아예 withAuth hoc 에다가 login state 업데이트 하는걸 붙여넣는건 어떨까요?
> 
> 저도 그게 훨씬 직관적이라고 생각해서 그렇게 구현해봤는데 withAuth가 컴포넌트가 아니라서 내부에서 dispatch를 사용할수가 없다고 하더라구요. 대안으로 저 두군데에다가 dispatch를 심어놨습니다

아 그런가요?? 살짝 해봤는데

![image](https://user-images.githubusercontent.com/32632221/83283753-a934a000-a216-11ea-9da5-430251aedea8.png)

이런식으로 하면 에러가 안나는데 어떤가요

**Comment by bbumjun** [comment]
> 아

엇 useEffect안에 넣는 식으로 하니까 잘되네요..ㅋㅋㅋㅋ 
withAuth에서 업데이트 하는 방식으로 가겠습니다 ㅎㅎ
